namespace Sa.Outbox.PostgreSql.Configuration;

/// <summary>Represents the settings for configuring the Outbox tables in PostgreSQL.</summary>
public sealed class PgOutboxTableSettings
{
    /// <summary>Contains default values for schema and table names.</summary>
    public static class Defaults
    {
        /// <summary>The default database schema name ("public").</summary>
        public const string DatabaseSchemaName = "public";

        /// <summary>The default base table name ("outbox"), from which all six table names derive.</summary>
        public const string DatabaseTableName = "outbox";
    }

    /// <summary>Gets or sets the database schema name that owns all six outbox tables. Default is "public".</summary>
    public string DatabaseSchemaName { get; set; } = Defaults.DatabaseSchemaName;

    /// <summary>The active task queue table (read-write, SKIP LOCKED). Table name equals the base table name.</summary>
    public TaskQueueTable TaskQueue { get; } = new();

    /// <summary>The source messages table (read-only, bulk BINARY COPY target).</summary>
    public MessageTable Message { get; } = new();

    /// <summary>The delivery history table (read-only).</summary>
    public DeliveryTable Delivery { get; } = new();

    /// <summary>The permanent errors table.</summary>
    public ErrorTable Error { get; } = new();

    /// <summary>The message-type registry table (type id ↔ name). No FillFactor property.</summary>
    public TypeTable Type { get; } = new();

    /// <summary>The consumer-group offsets table (advisory-locked). No FillFactor property.</summary>
    public OffsetTable Offset { get; } = new();

    /// <summary>Message table fields (append-only table, BINARY COPY target).</summary>
    public sealed class MessageTable
    {
        /// <summary>The table name suffix ("__msg$").</summary>
        public const string Suffix = "__msg$";

        /// <summary>Gets or sets the table name. Default is "{Defaults.DatabaseTableName}{Suffix}" (e.g. "outbox__msg$").</summary>
        public string TableName { get; set; } = $"{Defaults.DatabaseTableName}{Suffix}";

        /// <summary>Gets or sets the fill factor (1–100). PostgreSQL constraint — throws <see cref="ArgumentOutOfRangeException"/> outside this range.</summary>
        public int FillFactor
        {
            get => _fillFactor;
            set
            {
                if (value < 1 || value > 100)
                    throw new ArgumentOutOfRangeException(
                        nameof(value), value,
                        "FillFactor must be between 1 and 100 (PostgreSQL constraint).");
                _fillFactor = value;
            }
        }
        private int _fillFactor = 100;

        /// <summary>Gets the column definitions for the message table.</summary>
        public TableFields Fields { get; } = new();

        /// <summary>Column definitions for the message table.</summary>
        public sealed class TableFields
        {
            /// <summary>Message id — UUID v7, generated by the application. Partition sort key and consumption offset.</summary>
            public string MsgId { get; set; } = OutboxFieldDefaults.MsgId;

            /// <summary>Tenant id — first partitioning key.</summary>
            public string TenantId { get; set; } = OutboxFieldDefaults.TenantId;

            /// <summary>Message part — second partitioning key.</summary>
            public string MsgPart { get; set; } = OutboxFieldDefaults.MsgPart;

            /// <summary>Optional payload id supplied by the publisher.</summary>
            public string MsgPayloadId { get; set; } = OutboxFieldDefaults.MsgPayloadId;

            /// <summary>Hash of the payload type (murmurHash3), matching the __type$ registry.</summary>
            public string MsgPayloadType { get; set; } = OutboxFieldDefaults.MsgPayloadType;

            /// <summary>Serialized message payload.</summary>
            public string MsgPayload { get; set; } = OutboxFieldDefaults.MsgPayload;

            /// <summary>Payload size in bytes.</summary>
            public string MsgPayloadSize { get; set; } = OutboxFieldDefaults.MsgPayloadSize;

            /// <summary>Creation time (ticks) — partition timestamp column.</summary>
            public string MsgCreatedAt { get; set; } = OutboxFieldDefaults.MsgCreatedAt;

            /// <summary>Returns the exact PostgreSQL column definitions used at table creation.</summary>
            public string[] All() =>
            [
                $"{MsgId} UUID NOT NULL, -- UUID v7 is gen by app",
                $"{TenantId} INT NOT NULL DEFAULT 0",
                $"{MsgPart} TEXT NOT NULL",
                $"{MsgPayloadId} TEXT NOT NULL DEFAULT ''",
                $"{MsgPayloadType} BIGINT NOT NULL DEFAULT 0",
                $"{MsgPayload} BYTEA NOT NULL",
                $"{MsgPayloadSize} INT NOT NULL DEFAULT 0",
                $"{MsgCreatedAt} BIGINT NOT NULL DEFAULT 0"
            ];
        }
    }

    /// <summary>Task queue table fields (read-write table, SKIP LOCKED).</summary>
    public sealed class TaskQueueTable
    {
        /// <summary>Gets or sets the table name. Default is <see cref="Defaults.DatabaseTableName"/> (e.g. "outbox").</summary>
        public string TableName { get; set; } = Defaults.DatabaseTableName;

        /// <summary>Gets or sets the fill factor (1–100). PostgreSQL constraint — throws <see cref="ArgumentOutOfRangeException"/> outside this range.</summary>
        public int FillFactor
        {
            get => _fillFactor;
            set
            {
                if (value < 1 || value > 100)
                    throw new ArgumentOutOfRangeException(
                        nameof(value), value,
                        "FillFactor must be between 1 and 100 (PostgreSQL constraint).");
                _fillFactor = value;
            }
        }
        private int _fillFactor = 65;

        /// <summary>Gets the column definitions for the task queue table.</summary>
        public TableFields Fields { get; } = new();

        /// <summary>Column definitions for the task queue table.</summary>
        public sealed class TableFields
        {
            /// <summary>Task surrogate id.</summary>
            public string TaskId { get; set; } = OutboxFieldDefaults.TaskId;

            /// <summary>Consumer group — second partitioning key.</summary>
            public string ConsumerGroup { get; set; } = OutboxFieldDefaults.ConsumerGroup;

            /// <summary>Lock TTL (ticks) — consumers competing with SKIP LOCKED skip rows whose lock is still valid.</summary>
            public string TaskLockExpiresOn { get; set; } = OutboxFieldDefaults.TaskLockExpiresOn;

            /// <summary>Transaction / correlation id of the worker processing the task.</summary>
            public string TaskTransactId { get; set; } = OutboxFieldDefaults.TaskTransactId;

            // Message references
            /// <summary>Reference to the source message (v7 UUID).</summary>
            public string MsgId { get; set; } = OutboxFieldDefaults.MsgId;

            /// <summary>Message part (denormalized).</summary>
            public string MsgPart { get; set; } = OutboxFieldDefaults.MsgPart;

            /// <summary>Tenant id — first partitioning key.</summary>
            public string TenantId { get; set; } = OutboxFieldDefaults.TenantId;

            /// <summary>Payload id (denormalized).</summary>
            public string MsgPayloadId { get; set; } = OutboxFieldDefaults.MsgPayloadId;

            /// <summary>Type hash (denormalized).</summary>
            public string MsgPayloadType { get; set; } = OutboxFieldDefaults.MsgPayloadType;

            /// <summary>Message creation time (denormalized).</summary>
            public string MsgCreatedAt { get; set; } = OutboxFieldDefaults.MsgCreatedAt;

            // Delivery information
            /// <summary>Id of the delivery record in __log$.</summary>
            public string DeliveryId { get; set; } = OutboxFieldDefaults.DeliveryId;

            /// <summary>Delivery attempt counter.</summary>
            public string DeliveryAttempt { get; set; } = OutboxFieldDefaults.DeliveryAttempt;

            /// <summary>Delivery status code; 0 = DeliveryStatusCode.Pending.</summary>
            public string DeliveryStatusCode { get; set; } = OutboxFieldDefaults.DeliveryStatusCode;

            /// <summary>Free-text status / error message.</summary>
            public string DeliveryStatusMessage { get; set; } = OutboxFieldDefaults.DeliveryStatusMessage;

            /// <summary>Time the delivery started (ticks).</summary>
            public string DeliveryCreatedAt { get; set; } = OutboxFieldDefaults.DeliveryCreatedAt;

            // Error reference
            /// <summary>Reference to the __error$ row for permanent failures.</summary>
            public string ErrorId { get; set; } = OutboxFieldDefaults.ErrorId;

            /// <summary>Task creation time — partition timestamp column.</summary>
            public string TaskCreatedAt { get; set; } = OutboxFieldDefaults.TaskCreatedAt;

            /// <summary>Returns the exact PostgreSQL column definitions used at table creation.</summary>
            public string[] All() =>
            [
                $"{TaskId} BIGSERIAL NOT NULL",
                $"{ConsumerGroup} TEXT NOT NULL",
                $"{TaskLockExpiresOn} BIGINT NOT NULL DEFAULT 0",
                $"{TaskTransactId} TEXT NOT NULL DEFAULT ''",
                $"{MsgId} UUID NOT NULL",
                $"{MsgPart} TEXT NOT NULL",
                $"{TenantId} INT NOT NULL DEFAULT 0",
                $"{MsgPayloadId} TEXT NOT NULL DEFAULT ''",
                $"{MsgPayloadType} BIGINT NOT NULL DEFAULT 0",
                $"{MsgCreatedAt} BIGINT NOT NULL DEFAULT 0",
                $"{DeliveryId} BIGINT NOT NULL DEFAULT 0",
                $"{DeliveryAttempt} INT NOT NULL DEFAULT 0",
                $"{DeliveryStatusCode} INT NOT NULL DEFAULT {(int)Outbox.Delivery.DeliveryStatusCode.Pending}",
                $"{DeliveryStatusMessage} TEXT NOT NULL DEFAULT ''",
                $"{DeliveryCreatedAt} BIGINT NOT NULL DEFAULT 0",
                $"{ErrorId} BIGINT NOT NULL DEFAULT 0",
                $"{TaskCreatedAt} BIGINT NOT NULL DEFAULT 0"
            ];
        }
    }

    /// <summary>Delivery table fields (read-only table).</summary>
    public sealed class DeliveryTable
    {
        /// <summary>The table name suffix ("__log$").</summary>
        public const string Suffix = "__log$";

        /// <summary>Gets or sets the fill factor (1–100). PostgreSQL constraint — throws <see cref="ArgumentOutOfRangeException"/> outside this range.</summary>
        public int FillFactor
        {
            get => _fillFactor;
            set
            {
                if (value < 1 || value > 100)
                    throw new ArgumentOutOfRangeException(
                        nameof(value), value,
                        "FillFactor must be between 1 and 100 (PostgreSQL constraint).");
                _fillFactor = value;
            }
        }
        private int _fillFactor = 100;

        /// <summary>Gets or sets the table name. Default is "{Defaults.DatabaseTableName}{Suffix}" (e.g. "outbox__log$").</summary>
        public string TableName { get; set; } = $"{Defaults.DatabaseTableName}{Suffix}";

        /// <summary>Gets the column definitions for the delivery table.</summary>
        public TableFields Fields { get; } = new();

        /// <summary>Column definitions for the delivery table.</summary>
        public sealed class TableFields
        {
            /// <summary>Delivery record id.</summary>
            public string DeliveryId { get; set; } = OutboxFieldDefaults.DeliveryId;

            /// <summary>Final delivery status; 0 = Pending.</summary>
            public string DeliveryStatusCode { get; set; } = OutboxFieldDefaults.DeliveryStatusCode;

            /// <summary>Status / error message.</summary>
            public string DeliveryStatusMessage { get; set; } = OutboxFieldDefaults.DeliveryStatusMessage;

            /// <summary>Payload id.</summary>
            public string MsgPayloadId { get; set; } = OutboxFieldDefaults.MsgPayloadId;

            /// <summary>Tenant — first partitioning key.</summary>
            public string TenantId { get; set; } = OutboxFieldDefaults.TenantId;

            /// <summary>Consumer group — second partitioning key.</summary>
            public string ConsumerGroup { get; set; } = OutboxFieldDefaults.ConsumerGroup;

            /// <summary>Source task id.</summary>
            public string TaskId { get; set; } = OutboxFieldDefaults.TaskId;

            /// <summary>Task creation time.</summary>
            public string TaskCreatedAt { get; set; } = OutboxFieldDefaults.TaskCreatedAt;

            /// <summary>Worker transaction id.</summary>
            public string TaskTransactId { get; set; } = OutboxFieldDefaults.TaskTransactId;

            /// <summary>Lock TTL at delivery time.</summary>
            public string TaskLockExpiresOn { get; set; } = OutboxFieldDefaults.TaskLockExpiresOn;

            /// <summary>Reference to __error$ if the delivery ended in a permanent error.</summary>
            public string ErrorId { get; set; } = OutboxFieldDefaults.ErrorId;

            /// <summary>Delivery creation time — partition timestamp column.</summary>
            public string DeliveryCreatedAt { get; set; } = OutboxFieldDefaults.DeliveryCreatedAt;

            /// <summary>Returns the exact PostgreSQL column definitions used at table creation.</summary>
            public string[] All() =>
            [
                $"{DeliveryId} BIGSERIAL NOT NULL",
                $"{DeliveryStatusCode} INT NOT NULL DEFAULT {(int)Outbox.Delivery.DeliveryStatusCode.Pending}",
                $"{DeliveryStatusMessage} TEXT NOT NULL DEFAULT ''",
                $"{MsgPayloadId} TEXT NOT NULL DEFAULT ''",
                $"{TenantId} INT NOT NULL DEFAULT 0",
                $"{ConsumerGroup} TEXT NOT NULL",
                $"{TaskId} BIGINT NOT NULL DEFAULT 0",
                $"{TaskCreatedAt} BIGINT NOT NULL DEFAULT 0",
                $"{TaskTransactId} TEXT NOT NULL DEFAULT ''",
                $"{TaskLockExpiresOn} BIGINT NOT NULL DEFAULT 0",
                $"{ErrorId} BIGINT NOT NULL DEFAULT 0",
                $"{DeliveryCreatedAt} BIGINT NOT NULL DEFAULT 0"
            ];
        }
    }

    /// <summary>Error table fields (permanent errors, read-only).</summary>
    public sealed class ErrorTable
    {
        /// <summary>The table name suffix ("__error$").</summary>
        public const string Suffix = "__error$";

        /// <summary>Gets or sets the fill factor (1–100). PostgreSQL constraint — throws <see cref="ArgumentOutOfRangeException"/> outside this range.</summary>
        public int FillFactor
        {
            get => _fillFactor;
            set
            {
                if (value < 1 || value > 100)
                    throw new ArgumentOutOfRangeException(
                        nameof(value), value,
                        "FillFactor must be between 1 and 100 (PostgreSQL constraint).");
                _fillFactor = value;
            }
        }
        private int _fillFactor = 100;

        /// <summary>Gets or sets the table name. Default is "{Defaults.DatabaseTableName}{Suffix}" (e.g. "outbox__error$").</summary>
        public string TableName { get; set; } = $"{Defaults.DatabaseTableName}{Suffix}";

        /// <summary>Gets the column definitions for the error table.</summary>
        public TableFields Fields { get; } = new();

        /// <summary>Column definitions for the error table.</summary>
        public sealed class TableFields
        {
            /// <summary>Error record id.</summary>
            public string ErrorId { get; set; } = OutboxFieldDefaults.ErrorId;

            /// <summary>Error type name.</summary>
            public string ErrorType { get; set; } = OutboxFieldDefaults.ErrorType;

            /// <summary>Error message.</summary>
            public string ErrorMessage { get; set; } = OutboxFieldDefaults.ErrorMessage;

            /// <summary>Creation time — partition timestamp column.</summary>
            public string ErrorCreatedAt { get; set; } = OutboxFieldDefaults.ErrorCreatedAt;

            /// <summary>Returns the exact PostgreSQL column definitions used at table creation.</summary>
            public string[] All() =>
            [
                $"{ErrorId} BIGINT NOT NULL",
                $"{ErrorType} TEXT NOT NULL",
                $"{ErrorMessage} TEXT NOT NULL DEFAULT ''",
                $"{ErrorCreatedAt} BIGINT NOT NULL DEFAULT 0"
            ];
        }
    }

    /// <summary>Type table fields (message-type registry, type id ↔ name).</summary>
    public sealed class TypeTable
    {
        /// <summary>The table name suffix ("__type$").</summary>
        public const string Suffix = "__type$";

        /// <summary>Gets or sets the table name. Default is "{Defaults.DatabaseTableName}{Suffix}" (e.g. "outbox__type$").</summary>
        public string TableName { get; set; } = $"{Defaults.DatabaseTableName}{Suffix}";

        /// <summary>Gets the column definitions for the type table.</summary>
        public TableFields Fields { get; } = new();

        /// <summary>Column definitions for the type table.</summary>
        public sealed class TableFields
        {
            /// <summary>Type hash (murmurHash3) — primary key.</summary>
            public string TypeId { get; set; } = OutboxFieldDefaults.TypeId;

            /// <summary>Full type name.</summary>
            public string TypeName { get; set; } = OutboxFieldDefaults.TypeName;

            /// <summary>Returns the exact PostgreSQL column definitions used at table creation.</summary>
            public string[] All() =>
            [
                $"{TypeId} BIGINT NOT NULL",
                $"{TypeName} TEXT NOT NULL"
            ];
        }
    }

    /// <summary>Offset table fields (consumer-group offsets, advisory-locked).</summary>
    public sealed class OffsetTable
    {
        /// <summary>The table name suffix ("__offset$").</summary>
        public const string Suffix = "__offset$";

        /// <summary>Gets or sets the table name. Default is "{Defaults.DatabaseTableName}{Suffix}" (e.g. "outbox__offset$").</summary>
        public string TableName { get; set; } = $"{Defaults.DatabaseTableName}{Suffix}";

        /// <summary>Gets the column definitions for the offset table.</summary>
        public TableFields Fields { get; } = new();

        /// <summary>Column definitions for the offset table.</summary>
        public sealed class TableFields
        {
            /// <summary>Consumer group id — part of the primary key.</summary>
            public string ConsumerGroup { get; set; } = OutboxFieldDefaults.ConsumerGroup;

            /// <summary>Tenant — part of the primary key.</summary>
            public string TenantId { get; set; } = OutboxFieldDefaults.TenantId;

            /// <summary>Last consumed message id (UUID v7) — the offset is a v7 UUID, so it is time-ordered.</summary>
            public string GroupOffset { get; set; } = OutboxFieldDefaults.GroupOffset;

            /// <summary>Last offset update time.</summary>
            public string GroupUpdatedAt { get; set; } = OutboxFieldDefaults.GroupUpdatedAt;

            /// <summary>Returns the exact PostgreSQL column definitions used at table creation.</summary>
            public string[] All() =>
            [
                $"{ConsumerGroup} TEXT",
                $"{TenantId} INT NOT NULL DEFAULT 0",
                $"{GroupOffset} UUID NOT NULL DEFAULT '{Guid.Empty}'",
                $"{GroupUpdatedAt} TIMESTAMP WITH TIME ZONE DEFAULT NOW()"
            ];
        }
    }
}
