<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../Common.NuGet.Properties.xml" />

    <PropertyGroup>
        <Version>0.15.0</Version>
        <Description>WorkQueue wrapper for Channels</Description>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Sa.Utils.WorkQueue.Tests" />
    </ItemGroup>

</Project>
