<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../Common.NuGet.Properties.xml" />

    <PropertyGroup>
        <Version>0.12.0</Version>
        <Description>Async WAV file reader for .NET </Description>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>S3776</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Sa.MediaTests" />
    </ItemGroup>

</Project>
